name: Weather Forecast

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-weather:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Weather SVG
        uses: Aveek-Saha/github-weather-widget@master
        with:
          location: "Ho Chi Minh City"
          unit: "metric"
          show_icons: "true"
          show_feels_like: "true"
          show_humidity: "true"
          show_wind: "true"
          show_temp_max_min: "true"
          api_key: ${{ secrets.OPENWEATHERMAP_API_KEY }}
      - name: Push changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: 'Update weather forecast'
          add: '*.svg'
